name: Deploy to EC2

on:
  push:
    paths:
      - 'Backend/**' 
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "Backend/**"
          target: "/home/ubuntu/the-animals-are-starving"
      
      - name: Rebuild and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/the-animals-are-starving/Backend && \
            echo "Current directory: $(pwd)" && ls -al && \
            cat > .env << EOF
            PORT=${{ secrets.PROD_PORT }}
            DB_URI=${{ secrets.PROD_DB_URI }}
            EOF && \
            chmod 600 .env && \
            docker-compose -f docker-compose.yml down && \
            docker-compose -f docker-compose.yml --env-file .env build && \
            docker-compose -f docker-compose.yml --env-file .env up -d
