name: Deploy to EC2

on:
  push:
    paths:
      - 'Backend/**' 
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "Backend/**"
          target: "/home/ubuntu/the-animals-are-starving"
      
      - name: Rebuild and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            # Change to the backend directory
            cd /home/ubuntu/the-animals-are-starving/Backend
            
            # Debug: Verify current directory and list files
            echo "Current directory: $(pwd)"
            ls -al

            cat > .env << EOF
            PORT=${{ secrets.PROD_PORT }}
            DB_URI=${{ secrets.PROD_DB_URI }}
            FIREBASE_SERVICE_ACCOUNT=${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
            EOF

            # Set proper permissions for .env
            chmod 600 .env

            # Use absolute paths for docker-compose
            docker-compose -f /home/ubuntu/the-animals-are-starving/Backend/docker-compose.yml down
            docker-compose -f /home/ubuntu/the-animals-are-starving/Backend/docker-compose.yml --env-file /home/ubuntu/the-animals-are-starving/Backend/.env build
            docker-compose -f /home/ubuntu/the-animals-are-starving/Backend/docker-compose.yml --env-file /home/ubuntu/the-animals-are-starving/Backend/.env up -d