name: Mirror Repository

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Check if token is set
        run: |
          if [ -z "${{ secrets.MIRROR_REPO_TOKEN }}" ]; then
            echo "MIRROR_REPO_TOKEN is empty!";
            exit 1;
          else
            echo "MIRROR_REPO_TOKEN is set.";
          fi
          
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Mirror Repository
        env:
          MIRROR_REPO: https://matthewfung04:${{ secrets.MIRROR_REPO_TOKEN }}@github.com/The-Animals-are-Starving/the-animals-are-starving.git
        run: |
          git remote remove mirror || true
          git remote add mirror "$MIRROR_REPO"
          git push mirror --all --force
          git push mirror --tags --force
